/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PolyX } from "./PolyX";
export * as factories from "./factories";
export { PolyX__factory } from "./factories/PolyX__factory";
