/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace PolyX {
  export type PostStruct = {
    id: BigNumberish;
    author: AddressLike;
    content: string;
    timestamp: BigNumberish;
    postType: BigNumberish;
    referenceId: BigNumberish;
    likeCount: BigNumberish;
    retweetCount: BigNumberish;
    quoteCount: BigNumberish;
  };

  export type PostStructOutput = [
    id: bigint,
    author: string,
    content: string,
    timestamp: bigint,
    postType: bigint,
    referenceId: bigint,
    likeCount: bigint,
    retweetCount: bigint,
    quoteCount: bigint
  ] & {
    id: bigint;
    author: string;
    content: string;
    timestamp: bigint;
    postType: bigint;
    referenceId: bigint;
    likeCount: bigint;
    retweetCount: bigint;
    quoteCount: bigint;
  };
}

export interface PolyXInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "batchGetPosts"
      | "createPost"
      | "getPost"
      | "hasLiked"
      | "hasRetweeted"
      | "like"
      | "nextPostId"
      | "quote"
      | "retweet"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "Liked" | "PostCreated" | "Quoted" | "Retweeted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "batchGetPosts",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "createPost",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getPost",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasLiked",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRetweeted",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "like",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextPostId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "quote",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "retweet",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "batchGetPosts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createPost", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getPost", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasLiked", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasRetweeted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "like", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nextPostId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "quote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "retweet", data: BytesLike): Result;
}

export namespace LikedEvent {
  export type InputTuple = [
    postId: BigNumberish,
    user: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [postId: bigint, user: string, timestamp: bigint];
  export interface OutputObject {
    postId: bigint;
    user: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PostCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    author: AddressLike,
    postType: BigNumberish,
    referenceId: BigNumberish,
    content: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    author: string,
    postType: bigint,
    referenceId: bigint,
    content: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    id: bigint;
    author: string;
    postType: bigint;
    referenceId: bigint;
    content: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuotedEvent {
  export type InputTuple = [
    postId: BigNumberish,
    originalId: BigNumberish,
    user: AddressLike,
    timestamp: BigNumberish,
    content: string
  ];
  export type OutputTuple = [
    postId: bigint,
    originalId: bigint,
    user: string,
    timestamp: bigint,
    content: string
  ];
  export interface OutputObject {
    postId: bigint;
    originalId: bigint;
    user: string;
    timestamp: bigint;
    content: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RetweetedEvent {
  export type InputTuple = [
    postId: BigNumberish,
    originalId: BigNumberish,
    user: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    postId: bigint,
    originalId: bigint,
    user: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    postId: bigint;
    originalId: bigint;
    user: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PolyX extends BaseContract {
  connect(runner?: ContractRunner | null): PolyX;
  waitForDeployment(): Promise<this>;

  interface: PolyXInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  batchGetPosts: TypedContractMethod<
    [ids: BigNumberish[]],
    [PolyX.PostStructOutput[]],
    "view"
  >;

  createPost: TypedContractMethod<
    [logicalUser: AddressLike, content: string],
    [bigint],
    "nonpayable"
  >;

  getPost: TypedContractMethod<
    [postId: BigNumberish],
    [PolyX.PostStructOutput],
    "view"
  >;

  hasLiked: TypedContractMethod<
    [postId: BigNumberish, user: AddressLike],
    [boolean],
    "view"
  >;

  hasRetweeted: TypedContractMethod<
    [postId: BigNumberish, user: AddressLike],
    [boolean],
    "view"
  >;

  like: TypedContractMethod<
    [logicalUser: AddressLike, postId: BigNumberish],
    [void],
    "nonpayable"
  >;

  nextPostId: TypedContractMethod<[], [bigint], "view">;

  quote: TypedContractMethod<
    [logicalUser: AddressLike, originalId: BigNumberish, content: string],
    [bigint],
    "nonpayable"
  >;

  retweet: TypedContractMethod<
    [logicalUser: AddressLike, originalId: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "batchGetPosts"
  ): TypedContractMethod<
    [ids: BigNumberish[]],
    [PolyX.PostStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "createPost"
  ): TypedContractMethod<
    [logicalUser: AddressLike, content: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getPost"
  ): TypedContractMethod<
    [postId: BigNumberish],
    [PolyX.PostStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasLiked"
  ): TypedContractMethod<
    [postId: BigNumberish, user: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasRetweeted"
  ): TypedContractMethod<
    [postId: BigNumberish, user: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "like"
  ): TypedContractMethod<
    [logicalUser: AddressLike, postId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "nextPostId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "quote"
  ): TypedContractMethod<
    [logicalUser: AddressLike, originalId: BigNumberish, content: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "retweet"
  ): TypedContractMethod<
    [logicalUser: AddressLike, originalId: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getEvent(
    key: "Liked"
  ): TypedContractEvent<
    LikedEvent.InputTuple,
    LikedEvent.OutputTuple,
    LikedEvent.OutputObject
  >;
  getEvent(
    key: "PostCreated"
  ): TypedContractEvent<
    PostCreatedEvent.InputTuple,
    PostCreatedEvent.OutputTuple,
    PostCreatedEvent.OutputObject
  >;
  getEvent(
    key: "Quoted"
  ): TypedContractEvent<
    QuotedEvent.InputTuple,
    QuotedEvent.OutputTuple,
    QuotedEvent.OutputObject
  >;
  getEvent(
    key: "Retweeted"
  ): TypedContractEvent<
    RetweetedEvent.InputTuple,
    RetweetedEvent.OutputTuple,
    RetweetedEvent.OutputObject
  >;

  filters: {
    "Liked(uint256,address,uint256)": TypedContractEvent<
      LikedEvent.InputTuple,
      LikedEvent.OutputTuple,
      LikedEvent.OutputObject
    >;
    Liked: TypedContractEvent<
      LikedEvent.InputTuple,
      LikedEvent.OutputTuple,
      LikedEvent.OutputObject
    >;

    "PostCreated(uint256,address,uint8,uint256,string,uint256)": TypedContractEvent<
      PostCreatedEvent.InputTuple,
      PostCreatedEvent.OutputTuple,
      PostCreatedEvent.OutputObject
    >;
    PostCreated: TypedContractEvent<
      PostCreatedEvent.InputTuple,
      PostCreatedEvent.OutputTuple,
      PostCreatedEvent.OutputObject
    >;

    "Quoted(uint256,uint256,address,uint256,string)": TypedContractEvent<
      QuotedEvent.InputTuple,
      QuotedEvent.OutputTuple,
      QuotedEvent.OutputObject
    >;
    Quoted: TypedContractEvent<
      QuotedEvent.InputTuple,
      QuotedEvent.OutputTuple,
      QuotedEvent.OutputObject
    >;

    "Retweeted(uint256,uint256,address,uint256)": TypedContractEvent<
      RetweetedEvent.InputTuple,
      RetweetedEvent.OutputTuple,
      RetweetedEvent.OutputObject
    >;
    Retweeted: TypedContractEvent<
      RetweetedEvent.InputTuple,
      RetweetedEvent.OutputTuple,
      RetweetedEvent.OutputObject
    >;
  };
}
